### ISSUE TITLE
Small Hint

### ISSUE THREAD

**Issue by zellx3** [BaseMax/cpp-ostream-istream-example#1]
Normally it's better to have an operator as part of your class to capsulate everything.

**Comment by BaseMax** [comment]
Hi Mohammad;

Thanks for your message.

Yeah; Also at next step we need to use `friend class`.
https://en.cppreference.com/w/cpp/language/friend

```cpp
friend ostream &operator<<(ostream &out, const Pill &pill)
```

If you are interested in participating, I accept and merge and Thank you.
